-- CreateTable
CREATE TABLE "User" (
    "id" SERIAL NOT NULL,
    "email" TEXT NOT NULL,
    "name" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "User_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "contareceber" (
    "codigo" INTEGER NOT NULL,
    "descontoprogressivo" INTEGER,
    "origemnegociacaoreceber" INTEGER,
    "contacorrente" INTEGER,
    "funcionario" INTEGER,
    "pessoa" INTEGER,
    "matriculaaluno" TEXT,
    "centroreceita" INTEGER,
    "parcela" TEXT,
    "codigobarra" TEXT,
    "nrdocumento" TEXT,
    "multaporcentagem" DOUBLE PRECISION,
    "multa" DECIMAL(65,30),
    "juroporcentagem" DOUBLE PRECISION,
    "juro" DECIMAL(65,30),
    "valordesconto" DECIMAL(65,30),
    "valor" DECIMAL(65,30),
    "datavencimento" TIMESTAMP(3),
    "descricaopagamento" TEXT,
    "situacao" TEXT,
    "tipoorigem" TEXT,
    "codorigem" TEXT,
    "data" TIMESTAMP(3),
    "candidato" INTEGER,
    "tipopessoa" TEXT,
    "valorrecebido" DECIMAL(65,30),
    "tipodesconto" TEXT,
    "unidadeensino" INTEGER,
    "valordescontorecebido" DECIMAL(65,30),
    "descontoinstituicao" DECIMAL(65,30),
    "descontoconvenio" DECIMAL(65,30),
    "convenio" INTEGER,
    "tipoboleto" TEXT,
    "linhadigitavelcodigobarras" TEXT,
    "beneficiario" INTEGER,
    "nossonumero" TEXT,
    "parceiro" INTEGER,
    "matriculaperiodo" INTEGER,
    "valordescontoprogressivo" DECIMAL(65,30),
    "tituloimportadosistemalegado" BOOLEAN,
    "recebimentobancario" BOOLEAN,
    "ordemdescontoaluno" INTEGER,
    "ordemdescontoalunovalorcheio" BOOLEAN,
    "ordemplanodesconto" INTEGER,
    "ordemplanodescontovalorcheio" BOOLEAN,
    "ordemconvenio" INTEGER,
    "ordemconveniovalorcheio" BOOLEAN,
    "ordemdescontoprogressivo" INTEGER,
    "ordemdescontoprogressivovalorcheio" BOOLEAN,
    "justificativadesconto" TEXT,
    "codigoantsei" INTEGER,
    "impressaoboletorealizada" BOOLEAN,
    "descontoprogressivoutilizado" TEXT,
    "valordescontocalculadoprimeirafaixadescontos" DECIMAL(65,30),
    "valordescontocalculadosegundafaixadescontos" DECIMAL(65,30),
    "valordescontocalculadoterceirafaixadescontos" DECIMAL(65,30),
    "valordescontocalculadoquartafaixadescontos" DECIMAL(65,30),
    "valordescontolancadorecebimento" DECIMAL(65,30),
    "valorcalculadodescontolancadorecebimento" DECIMAL(65,30),
    "tipodescontolancadorecebimento" TEXT,
    "valordescontoalunojacalculado" DECIMAL(65,30),
    "dataarquivoremessa" TIMESTAMP(3),
    "updated" TIMESTAMP(3),
    "acrescimo" DECIMAL(65,30),
    "linha" TEXT,
    "usadescontocompostoplanodesconto" BOOLEAN,
    "codigorenegociacao" INTEGER,
    "nossonumerobanco" TEXT,
    "responsavelfinanceiro" INTEGER,
    "taxaboleto" DECIMAL(65,30),
    "contareceberjaenviadaaluno" BOOLEAN,
    "turma" INTEGER,
    "duplicidadetratada" BOOLEAN,
    "fornecedor" INTEGER,
    "dataprocessamentovalorreceber" TIMESTAMP(3),
    "valorrecebercalculado" DECIMAL(65,30),
    "valorjurocalculado" DECIMAL(65,30),
    "valormultacalculado" DECIMAL(65,30),
    "valordescontocalculado" DECIMAL(65,30),
    "contareceberagrupada" INTEGER,
    "codigoant" INTEGER,
    "tabelaant" TEXT,
    "valorcusteadocontareceber" DECIMAL(65,30),
    "valorbasecontareceber" DECIMAL(65,30),
    "nossonumeroantigo" TEXT,
    "codigotempexcluir" INTEGER,
    "datacompetencia" TIMESTAMP(3),
    "nossonumerotemp" TEXT,
    "valorbasecontareceberant" DECIMAL(65,30),
    "sequencialnossonumero" BIGINT,
    "usuariodesbloqueoudescontorecebimento" INTEGER,
    "datausuariodesbloqueoudescontorecebimento" TIMESTAMP(3),
    "processamentointegracaofinanceiradetalhe" INTEGER,
    "possuipendenciasfinanceirasexternas" BOOLEAN,
    "motivocancelamento" TEXT,
    "datacancelamento" TIMESTAMP(3),
    "responsavelcancelamento" INTEGER,
    "notafiscalsaidaservico" INTEGER,
    "valordescontorateio" DECIMAL(65,30),
    "identificacaotitulobanco" TEXT,
    "contaremetidacomalteracao" BOOLEAN,
    "pagocomdcc" BOOLEAN,
    "contaremetidacomalteracao_datadescprogressivo" BOOLEAN,
    "contaremetidacomalteracao_datavencimento" BOOLEAN,
    "contaremetidacomalteracao_valorbase" BOOLEAN,
    "contaremetidacomalteracao_valorcomabatimentoadicionadooumodific" BOOLEAN,
    "contaremetidacomalteracao_valorcomabatimentoremovido" BOOLEAN,
    "contaremetidacomalteracao_valordescprogressivo" BOOLEAN,
    "unidadeensinofinanceira" INTEGER,
    "valorindicereajuste" DECIMAL(65,30),
    "valorreajustediferencaparcelarecebidaouenviadaremessa" DECIMAL(65,30),
    "registrocobrancacontareceber" INTEGER,
    "contaeditadamanualmente" BOOLEAN,
    "utilizardescontoprogressivomanual" BOOLEAN,
    "dialimite1" INTEGER,
    "dialimite2" INTEGER,
    "dialimite3" INTEGER,
    "dialimite4" INTEGER,
    "possuifiesintegracaofinanceiras" BOOLEAN,
    "valorindicereajusteporatraso" DECIMAL(65,30),
    "indicereajustepadraoporatraso" INTEGER,
    "liberadodoindicereajusteporatraso" BOOLEAN,
    "contageradaapartirvalormulta_phl" BOOLEAN,
    "datalimiteprimeirafaixadescontos" TIMESTAMP(3),
    "datalimitesegundafaixadescontos" TIMESTAMP(3),
    "datalimiteterceirafaixadescontos" TIMESTAMP(3),
    "datalimitequartafaixadescontos" TIMESTAMP(3),
    "nomesacado" TEXT,
    "created" TIMESTAMP(3),
    "codigocreated" INTEGER,
    "nomecreated" TEXT,
    "codigoupdated" INTEGER,
    "nomeupdated" TEXT,
    "valortaxarepassecartao" DECIMAL(65,30),
    "valorestornadocartao" DECIMAL(65,30),
    "origeminclusao" TEXT,
    "token" TEXT,
    "datacorrecaolancamentocontabil" TIMESTAMP(3),
    "empresafinanceira" TEXT,
    "codigointegracaoempresafinanceira" TEXT,
    "notafiscalsap" INTEGER,
    "urlboletoempresafinanceira" TEXT,
    "parcelabloqueadaempresafinanceira" BOOLEAN,
    "motivobloqueadaempresafinanceira" TEXT,
    "pagoparcialmenteempresafinanceira" BOOLEAN,
    "valorpagoparcialmenteempresafinanceira" DECIMAL(65,30),
    "pagoemacordoempresafinanceira" BOOLEAN,
    "codigoprotheus" TEXT,
    "codigoprodutoprotheus" TEXT,
    "codigopedidoprotheus" TEXT,
    "codigonaturezaoperacaoprotheus" TEXT,
    "mensagemnotaprotheus" TEXT,
    "pagoiesempresafinanceira" BOOLEAN,

    CONSTRAINT "contareceber_pkey" PRIMARY KEY ("codigo")
);

-- CreateTable
CREATE TABLE "pessoa" (
    "codigo" INTEGER NOT NULL,
    "necessidadesespeciais" TEXT,
    "tituloeleitoral" TEXT,
    "orgaoemissor" TEXT,
    "estadoemissaorg" TEXT,
    "dataemissaorg" TIMESTAMP(3),
    "certificadomilitar" TEXT,
    "rg" TEXT,
    "cpf" TEXT,
    "nacionalidade" INTEGER,
    "naturalidade" INTEGER,
    "datanasc" TIMESTAMP(3),
    "email" TEXT,
    "celular" TEXT,
    "telefonerecado" TEXT,
    "telefoneres" TEXT,
    "estadocivil" TEXT,
    "sexo" TEXT,
    "cidade" INTEGER,
    "complemento" TEXT,
    "cep" TEXT,
    "numero" TEXT,
    "setor" TEXT,
    "endereco" TEXT,
    "nome" TEXT,
    "aluno" BOOLEAN,
    "professor" BOOLEAN,
    "funcionario" BOOLEAN,
    "candidato" BOOLEAN,
    "membrocomunidade" BOOLEAN,
    "paginapessoal" TEXT,
    "csspadrao" TEXT,
    "perfileconomico" INTEGER,
    "atuacomodocente" TEXT,
    "ativo" BOOLEAN,
    "idalunoinep" TEXT,
    "corraca" TEXT,
    "deficiencia" TEXT,
    "passaporte" TEXT,
    "nomefiador" TEXT,
    "enderecofiador" TEXT,
    "telefonefiador" TEXT,
    "cpffiador" TEXT,
    "tiponecessidadesespeciais" TEXT,
    "celularfiador" TEXT,
    "valorcsstopologo" TEXT,
    "valorcssbackground" TEXT,
    "valorcssmenu" TEXT,
    "arquivoimagem" INTEGER,
    "codigoantsei" INTEGER,
    "email2" TEXT,
    "dataultimaalteracao" TIMESTAMP(3),
    "reponsavelultimaalteracao" INTEGER,
    "coordenador" BOOLEAN,
    "enviarcomunicadopessoa" BOOLEAN,
    "access" BOOLEAN,
    "autocad" BOOLEAN,
    "coreldraw" BOOLEAN,
    "espanhol" BOOLEAN,
    "espanholnivel" TEXT,
    "excel" BOOLEAN,
    "frances" BOOLEAN,
    "francesnivel" TEXT,
    "ingles" BOOLEAN,
    "inglesnivel" TEXT,
    "internet" BOOLEAN,
    "microsiga" BOOLEAN,
    "outrosidiomas" TEXT,
    "outrosidiomasnivel" TEXT,
    "outrossoftwares" TEXT,
    "photoshop" BOOLEAN,
    "powerpoint" BOOLEAN,
    "sap" BOOLEAN,
    "windows" BOOLEAN,
    "word" BOOLEAN,
    "telefonecomer" TEXT,
    "nomeempresa" TEXT,
    "enderecoempresa" TEXT,
    "cargopessoaempresa" TEXT,
    "cepempresa" TEXT,
    "complementoempresa" TEXT,
    "setorempresa" TEXT,
    "cidadeempresa2" INTEGER,
    "cidadeempresa3" TEXT,
    "cidadeempresa" INTEGER,
    "possuifilho" BOOLEAN,
    "qtdfilhos" INTEGER,
    "participabancocurriculum" BOOLEAN,
    "informacoesverdadeiras" BOOLEAN,
    "divulgarmeusdados" BOOLEAN,
    "certidaonascimento" TEXT,
    "informacoesadicionais" TEXT,
    "codprospect" INTEGER,
    "gerenciapreinscricao" BOOLEAN,
    "curriculoatualizado" BOOLEAN,
    "seraza" BOOLEAN,
    "responsavellancamentoseraza" INTEGER,
    "datalancamentoseraza" TIMESTAMP(3),
    "pispasep" TEXT,
    "cepfiador" TEXT,
    "complementofiador" TEXT,
    "numeroendfiador" TEXT,
    "possuiacessovisaopais" BOOLEAN,
    "setorfiador" TEXT,
    "cepficador" TEXT,
    "cidadefiador" INTEGER,
    "codigofiliacao" INTEGER,
    "requisitante" BOOLEAN,
    "isentartaxaboleto" BOOLEAN,
    "ocultardadoscrm" BOOLEAN,
    "gravida" BOOLEAN,
    "canhoto" BOOLEAN,
    "portadornecessidadeespecial" BOOLEAN,
    "disciplinas" TEXT,
    "qtdvagascandidatou" INTEGER,
    "dataexpedicaotituloeleitoral" TIMESTAMP(3),
    "zonaeleitoral" TEXT,
    "dataexpedicaocertificadomilitar" TIMESTAMP(3),
    "orgaoexpedidorcertificadomilitar" TEXT,
    "codigoantresponsavelfinanceiro" TEXT,
    "codigoant" INTEGER,
    "tabelaant" TEXT,
    "situacaomilitar" TEXT,
    "dadospessoaisatualizado" BOOLEAN,
    "nomecenso" TEXT,
    "dataultimaatualizacaocadatral" TIMESTAMP(3),
    "grauparentesco" TEXT,
    "permiteenviarremessa" BOOLEAN,
    "senhacertificadoparadocumento" TEXT,
    "estadocivilfiador" TEXT,
    "datanascimentofiador" TIMESTAMP(3),
    "profissaofiador" TEXT,
    "rgfiador" TEXT,
    "paisfiador" INTEGER,
    "secaozonaeleitoral" TEXT,
    "tipomidiacaptacao" INTEGER,
    "nomebatismo" TEXT,
    "possuicadastrominhabiblioteca" BOOLEAN,
    "created" TIMESTAMP(3),
    "codigocreated" INTEGER,
    "nomecreated" TEXT,
    "updated" TIMESTAMP(3),
    "codigoupdated" INTEGER,
    "nomeupdated" TEXT,
    "falecido" BOOLEAN,
    "residecomresponsavel" BOOLEAN,
    "datahoravencimentocodigoautenticacao" TIMESTAMP(3),
    "codigoautenticacao" INTEGER,
    "idcrmeducacional" TEXT,
    "nomemedico" TEXT,
    "telefonemedico" TEXT,
    "planosaude" TEXT,
    "telefoneplanosaude" TEXT,
    "tiposanguineo" TEXT,
    "alergia" TEXT,
    "doencagrave" TEXT,
    "remedioespecial" TEXT,
    "diagnostico" TEXT,
    "apoiorecurso" TEXT,
    "tempoestendidoprova" BOOLEAN,
    "bloquearcontatocrm" BOOLEAN,
    "emancipado" BOOLEAN,
    "atualizardatacadastral" BOOLEAN,
    "autorizodivulgacaoinformacoesterceiros" BOOLEAN,
    "codigopessoasap" TEXT,
    "codigoautenticacaonavegador" TEXT,
    "tipoassinaturadocumentoenum" TEXT,
    "token" TEXT,
    "numerodocumentoestrangeiro" TEXT,
    "utilizardocumentoestrangeiro" BOOLEAN,
    "tipodocumentoestrangeiro" TEXT,
    "codigoplataformaa" INTEGER,
    "resideexterior" BOOLEAN,
    "paisresideexterior" INTEGER,
    "cidaderesideexterior" TEXT,
    "estadoresideexterior" TEXT,
    "codigopostal" TEXT,
    "codigointegracaopergamum" TEXT,
    "situacaointegracaopergamum" TEXT,
    "descricaosituacaointegracaopergamum" TEXT,
    "idcrmrdstation" TEXT,
    "idempresafinanceira" TEXT,
    "discalculia" BOOLEAN,
    "disgrafia" BOOLEAN,
    "dislalia" BOOLEAN,
    "dislexia" BOOLEAN,
    "transtornodeficitatencaohiperatividade" BOOLEAN,
    "transtornoprocessamentoauditivocentral" BOOLEAN,
    "recursoavaliacaoinepauxilioledor" BOOLEAN,
    "recursoavaliacaoinepauxiliotranscricao" BOOLEAN,
    "recursoavaliacaoinepauxiliointerprete" BOOLEAN,
    "recursoavaliacaoinepauxiliotradutorinterpretelibras" BOOLEAN,
    "recursoavaliacaoinepauxilioleituralabial" BOOLEAN,
    "recursoavaliacaoinepauxilioprovaampliada" BOOLEAN,
    "recursoavaliacaoinepauxilioprovasuperampliada" BOOLEAN,
    "recursoavaliacaoinepauxiliocdcomaudioparadeficientevisual" BOOLEAN,
    "recursoavaliacaoinepauxilioprovaportuguesasegundalinguasurdos" BOOLEAN,
    "recursoavaliacaoinepauxilioprovaemvideoemlibras" BOOLEAN,
    "recursoavaliacaoinepauxiliomaterialdidaticoembraille" BOOLEAN,
    "recursoavaliacaoinepauxilioprovaembraille" BOOLEAN,
    "recursoavaliacaoinepauxiliotempoadicional" BOOLEAN,
    "recursoavaliacaoinepauxilionenhum" BOOLEAN,
    "codigod2l" INTEGER,
    "registroacademico" TEXT,
    "codigointegracao" TEXT,
    "origemintegracao" TEXT,
    "idintegracao" TEXT,
    "cnpj" TEXT,
    "tipodocumento" TEXT,
    "inscricaomunicipal" TEXT,
    "inscricaoestadual" TEXT,
    "codigootm" INTEGER,
    "codigoprotheus" TEXT,

    CONSTRAINT "pessoa_pkey" PRIMARY KEY ("codigo")
);

-- CreateTable
CREATE TABLE "matricula" (
    "matricula" TEXT NOT NULL,
    "tipomidiacaptacao" INTEGER,
    "turno" INTEGER,
    "usuario" INTEGER,
    "inscricao" INTEGER,
    "situacaofinanceira" TEXT,
    "situacao" TEXT,
    "data" TIMESTAMP(3),
    "curso" INTEGER,
    "unidadeensino" INTEGER,
    "aluno" INTEGER,
    "tranferenciaentrada" INTEGER,
    "responsavelliberacaodesconto" INTEGER,
    "formaingresso" TEXT,
    "programareservavaga" TEXT,
    "financiamentoestudantil" TEXT,
    "apoiosocial" TEXT,
    "atividadecomplementar" TEXT,
    "anoingresso" TEXT,
    "semestreingresso" TEXT,
    "anoconclusao" TEXT,
    "semestreconclusao" TEXT,
    "disciplinasprocseletivo" TEXT,
    "fezenade" BOOLEAN,
    "dataenade" TIMESTAMP(3),
    "notaenade" DOUBLE PRECISION,
    "horascomplementares" INTEGER,
    "enade" INTEGER,
    "alunoabandonoucurso" BOOLEAN,
    "nomemonografia" TEXT,
    "datainiciocurso" TIMESTAMP(3),
    "dataconclusaocurso" TIMESTAMP(3),
    "observacaocomplementar" TEXT,
    "localarmazenamentodocumentosmatricula" TEXT,
    "descontochancela" BOOLEAN,
    "notamonografia" TEXT,
    "formacaoacademica" INTEGER,
    "updated" TIMESTAMP(3),
    "autorizacaocurso" INTEGER,
    "consultor" INTEGER,
    "tipomatricula" TEXT,
    "extensao" BOOLEAN,
    "matriculasuspensa" BOOLEAN,
    "databasesuspensao" TIMESTAMP(3),
    "dataenvionotificacao1" TIMESTAMP(3),
    "dataenvionotificacao2" TIMESTAMP(3),
    "dataenvionotificacao3" TIMESTAMP(3),
    "matriculaserasa" BOOLEAN,
    "dataatualizacaomatriculaformada" TIMESTAMP(3),
    "responsavelatualizacaomatriculaformada" INTEGER,
    "naoenviarmensagemcobranca" BOOLEAN,
    "qtddisciplinasextensao" INTEGER,
    "dataliberacaopendenciafinanceira" TIMESTAMP(3),
    "responsavelliberacaopendenciafinanceira" INTEGER,
    "formou" BOOLEAN,
    "alunoconcluiudisciplinasregulares" BOOLEAN,
    "dataalunoconcluiudisciplinasregulares" TIMESTAMP(3),
    "datacolacaograu" TIMESTAMP(3),
    "dataenvionotificacaopendenciadocumento" TIMESTAMP(3),
    "qtddiasadiarbloqueio" INTEGER,
    "adesivoinstituicaoentregue" BOOLEAN,
    "dataalteracaomatriculaserasa" TIMESTAMP(3),
    "usuariorespalteracaomatriculaserasa" INTEGER,
    "mesingresso" TEXT,
    "matriculaverificadaserasa" BOOLEAN,
    "liberarbloqueioalunoinadimplente" BOOLEAN,
    "datanotifcalunoinadimplente" TIMESTAMP(3),
    "dataprimeiranotinadimplencia" TIMESTAMP(3),
    "datasegundanotinadimplencia" TIMESTAMP(3),
    "dataterceiranotinadimplencia" TIMESTAMP(3),
    "codigoant" INTEGER,
    "tabelaant" TEXT,
    "statusimp" TEXT,
    "datacadastro" TIMESTAMP(3),
    "totalpontoprocseletivo" DECIMAL(65,30),
    "naoapresentarcenso" BOOLEAN,
    "dataprocessoseletivo" TIMESTAMP(3),
    "gradecurricularatual" INTEGER,
    "dataquartanotinadimplencia" TIMESTAMP(3),
    "dataenvionotificacao4" TIMESTAMP(3),
    "tipotrabalhoconclusaocurso" TEXT,
    "notaenem" DECIMAL(65,30),
    "observacaodiploma" TEXT,
    "canceladofinanceiro" BOOLEAN,
    "codigofinanceiromatricula" TEXT,
    "classificacaoingresso" TEXT,
    "semestreanoingressocenso" TEXT,
    "renovacaoreconhecimento" INTEGER,
    "bloquearemissaoboletomatmenvisaoaluno" BOOLEAN,
    "localprocessoseletivo" TEXT,
    "motivomatriculabloqueada" TEXT,
    "responsavelsuspensaomatricula" INTEGER,
    "responsavelcancelamentosuspensaomatricula" INTEGER,
    "datacancelamentosuspensaomatricula" TIMESTAMP(3),
    "motivocancelamentosuspensaomatricula" TEXT,
    "responsaveladiamentosuspensaomatricula" INTEGER,
    "dataadiamentosuspensaomatricula" TIMESTAMP(3),
    "motivoadiamentosuspensaomatricula" TEXT,
    "codigoinscricaoovg" TEXT,
    "dataemissaohistorico" TIMESTAMP(3),
    "permiteexecucaoreajustepreco" BOOLEAN,
    "motivocancelamentoreajustepreco" TEXT,
    "datacancelamentoreajustepreco" TIMESTAMP(3),
    "responsavelcancelamentoreajustepreco" INTEGER,
    "orientadormonografia" TEXT,
    "proficiencialinguaestrangeira" TEXT,
    "situacaoproficiencialinguaestrangeira" TEXT,
    "bloqueioporsolicitacaoliberacaomatricula" BOOLEAN,
    "considerarparcelasmaterialdidaticoreajustepreco" BOOLEAN,
    "permitirinclusaoexclusaodisciplinasrenovacao" BOOLEAN,
    "cargahorariamonografia" INTEGER,
    "titulacaoorientadormonografia" TEXT,
    "created" TIMESTAMP(3),
    "codigocreated" INTEGER,
    "nomecreated" TEXT,
    "codigoupdated" INTEGER,
    "nomeupdated" TEXT,
    "escolapublica" BOOLEAN,
    "datamonografia" TIMESTAMP(3),
    "ingressantecota" TEXT,
    "bolsasauxilios" BOOLEAN,
    "autodeclaracaopretopardoindigena" BOOLEAN,
    "normasmatricula" BOOLEAN,
    "financiamentoestudantilcenso" TEXT,
    "justificativacenso" TEXT,
    "tipomobilidadeacademica" TEXT,
    "mobilidadeacademicanacionaliesdestino" TEXT,
    "mobilidadeacademicainternacionalpaisdestino" TEXT,
    "idcrmeducacional" TEXT,
    "informacoescensorelativoano" TEXT,
    "datadefesatcc" TIMESTAMP(3),
    "datapublicacaoartigo" TIMESTAMP(3),
    "cargahorariamatrizcurricular" INTEGER,
    "areaconcentracaomestrado" TEXT,
    "datarealizacaoprovamestrado" TIMESTAMP(3),
    "dataexamequalificacaomestrado" TIMESTAMP(3),
    "matriculaanterior" TEXT,
    "origem" TEXT,
    "permitirassinarcontratopendenciadocumentacao" BOOLEAN,
    "codigoregistrocertifikedu" TEXT,
    "erroregistrocertifikedu" TEXT,
    "cupomdesconto" INTEGER,
    "codigoplataformaa" INTEGER,
    "unidadeensinopolo" INTEGER,
    "idnegociacaordstationcrm" TEXT,
    "motivobloqueiorenovacaomatricula" TEXT,
    "bloquearrenovacaomatricula" BOOLEAN,

    CONSTRAINT "matricula_pkey" PRIMARY KEY ("matricula")
);

-- CreateTable
CREATE TABLE "matriculaperiodo" (
    "codigo" INTEGER NOT NULL,
    "responsavelliberacaomatricula" INTEGER,
    "responsavelemissaoboletomatricula" INTEGER,
    "dataemissaoboletomatricula" TIMESTAMP(3),
    "dataliberacaomatricula" TIMESTAMP(3),
    "turma" INTEGER,
    "responsavelrenovacaomatricula" INTEGER,
    "periodoletivomatricula" INTEGER,
    "gradecurricular" INTEGER,
    "matricula" TEXT,
    "situacao" TEXT,
    "data" TIMESTAMP(3),
    "contareceber" INTEGER,
    "nrdocumento" TEXT,
    "unidadeensinocurso" INTEGER,
    "turmaperiodo" INTEGER,
    "semestre" TEXT,
    "ano" TEXT,
    "responsavelmatriculaforaprazo" INTEGER,
    "situacaomatriculaperiodo" TEXT,
    "processomatricula" INTEGER,
    "transferenciaentrada" INTEGER,
    "contratomatricula" INTEGER,
    "planofinanceirocurso" INTEGER,
    "condicaopagamentoplanofinanceirocurso" INTEGER,
    "matriculaperiodoprematricula" INTEGER,
    "nrdisciplinasincluidas" INTEGER,
    "nrdisciplinasexcluidas" INTEGER,
    "financeiromanual" BOOLEAN,
    "contratofiador" INTEGER,
    "reconheceudivida" BOOLEAN,
    "carneentregue" BOOLEAN,
    "codigoantsei" INTEGER,
    "datafechamentomatriculaperiodo" TIMESTAMP(3),
    "origemfechamentomatriculaperiodo" TEXT,
    "codigoorigemfechamentomatriculaperiodo" INTEGER,
    "usuarioresponsavelconfirmacaooucancelamentoprematricula" INTEGER,
    "bolsista" BOOLEAN,
    "contratoextensao" INTEGER,
    "alunotransferidounidade" BOOLEAN,
    "responsavelativacaofinanceiromanual" INTEGER,
    "dataativacaofinanceiromanual" TIMESTAMP(3),
    "aceitoutermocontratorenovacaoonline" BOOLEAN,
    "datanotificacaoabandonocurso" TIMESTAMP(3),
    "codigoant" INTEGER,
    "tabelaant" TEXT,
    "statusimp" TEXT,
    "motivoliberacaopgtomatricula" TEXT,
    "matriculaespecial" BOOLEAN,
    "observacaocriterioavaliacao" TEXT,
    "sequencialcodmatperalternativoboleto" INTEGER,
    "matriculaperiodoincluidaparacorrecaohistoricoforagrade" BOOLEAN,
    "deveatualizarnovaunidadeensinocurso" BOOLEAN,
    "dataaceitoutermocontratorenovacaoonline" TIMESTAMP(3),
    "categoriacondicaopagamento" TEXT,
    "databasegeracaoparcelas" TIMESTAMP(3),
    "datavencimentomatriculaespecifico" TIMESTAMP(3),
    "created" TIMESTAMP(3),
    "codigocreated" INTEGER,
    "nomecreated" TEXT,
    "updated" TIMESTAMP(3),
    "codigoupdated" INTEGER,
    "nomeupdated" TEXT,
    "nrparcelasperiodocalculo" INTEGER,
    "registroemmanutencao" BOOLEAN,
    "turnomatriculaanterior" INTEGER,
    "identificadoralteracaodados" TEXT,
    "geracaoparcelaautomatica" BOOLEAN,
    "alunoregular" BOOLEAN,
    "contratoaditivo" INTEGER,
    "codigoplataformaa" INTEGER,

    CONSTRAINT "matriculaperiodo_pkey" PRIMARY KEY ("codigo")
);

-- CreateTable
CREATE TABLE "turma" (
    "codigo" INTEGER NOT NULL,
    "situacao" TEXT,
    "curso" INTEGER,
    "periodoletivo" INTEGER,
    "turno" INTEGER,
    "unidadeensino" INTEGER,
    "gradecurricular" INTEGER,
    "nrminimomatricula" INTEGER,
    "nrmaximomatricula" INTEGER,
    "nrvagas" INTEGER,
    "identificadorturma" TEXT,
    "sala" TEXT,
    "turmaagrupada" BOOLEAN,
    "semestral" BOOLEAN,
    "anual" BOOLEAN,
    "configuracaoacademico" INTEGER,
    "planofinanceirocurso" INTEGER,
    "turmaprematricula" BOOLEAN,
    "tipochancela" TEXT,
    "porcentagemchancela" DOUBLE PRECISION,
    "valorfixochancela" DECIMAL(65,30),
    "valorporaluno" BOOLEAN,
    "codigoantsei" INTEGER,
    "databasegeracaoparcelas" TIMESTAMP(3),
    "grupodestinatarios" INTEGER,
    "chancela" INTEGER,
    "contacorrente" INTEGER,
    "qtdalunosestimado" INTEGER,
    "customedioaluno" DOUBLE PRECISION,
    "receitamediaaluno" DOUBLE PRECISION,
    "exigeniveladministrativoplanoorcamentario" BOOLEAN,
    "exigenivelacademicoplanoorcamentario" BOOLEAN,
    "exigecentrocustorequisitante" BOOLEAN,
    "utilizardadosmatrizboleto" BOOLEAN,
    "dataprevistafinalizacao" TIMESTAMP(3),
    "dataprevisaofinalizacao" TIMESTAMP(3),
    "observacao" TEXT,
    "codigoant" INTEGER,
    "tabelaant" TEXT,
    "identificadoturmatemporario" TEXT,
    "subturma" BOOLEAN,
    "turmaprincipal" INTEGER,
    "configuracaoead" INTEGER,
    "avaliacaoonline" INTEGER,
    "tiposubturma" TEXT,
    "apresentarrenovacaoonline" BOOLEAN,
    "abreviaturacurso" TEXT,
    "nrvagasinclusaoreposicao" INTEGER,
    "datacriacao" TIMESTAMP(3),
    "categoriacondicaopagamento" TEXT,
    "dataultimaalteracao" TIMESTAMP(3),
    "indicereajuste" INTEGER,
    "centroresultado" INTEGER,
    "digitoturma" TEXT,
    "codigoturnoapresentarcenso" INTEGER,
    "considerarturmaavaliacaoinstitucional" BOOLEAN,
    "created" TIMESTAMP(3),
    "codigocreated" INTEGER,
    "nomecreated" TEXT,
    "updated" TIMESTAMP(3),
    "codigoupdated" INTEGER,
    "nomeupdated" TEXT,
    "nrvagasenriquecimento" INTEGER,
    "estruturacurricularcensoformacaogeralbasica" BOOLEAN,
    "estruturacurricularcensoitinerarioformativo" BOOLEAN,
    "unidadecurriculareletivas" BOOLEAN,
    "unidadecurricularlibras" BOOLEAN,
    "unidadecurricularlinguaindigena" BOOLEAN,
    "unidadecurricularlingualiteraturaestrangeiraespanhol" BOOLEAN,
    "unidadecurricularlingualiteraturaestrangeirafrances" BOOLEAN,
    "unidadecurricularlingualiteraturaestrangeiraoutra" BOOLEAN,
    "unidadecurricularprojetovida" BOOLEAN,
    "unidadecurriculartrilhasaprofundamentoaprendizagens" BOOLEAN,
    "modalidadeturma" INTEGER,
    "unidadecurricularoutras" TEXT,
    "nrvagasextensao" INTEGER,
    "incompany" BOOLEAN,
    "tutorblackboard" INTEGER,
    "identificadorhierarquiablackboard" TEXT,
    "integracaosap" BOOLEAN,
    "areaitinerarioformativolinguagens" BOOLEAN,
    "areaitinerarioformativomatematica" BOOLEAN,
    "areaitinerarioformativocienciasnatureza" BOOLEAN,
    "areaitinerarioformativocienciahumanas" BOOLEAN,
    "areaitinerarioformativoformacaotecnicaprofissinal" BOOLEAN,

    CONSTRAINT "turma_pkey" PRIMARY KEY ("codigo")
);

-- CreateTable
CREATE TABLE "curso" (
    "codigo" INTEGER NOT NULL,
    "configuracaoacademico" INTEGER,
    "areaconhecimento" INTEGER,
    "regime" TEXT,
    "regimeaprovacao" TEXT,
    "periodicidade" TEXT,
    "datacriacao" TIMESTAMP(3),
    "nrregistrointerno" TEXT,
    "datapublicacaodo" TIMESTAMP(3),
    "nrperiodoletivo" INTEGER,
    "baselegal" TEXT,
    "niveleducacional" TEXT,
    "perfilegresso" TEXT,
    "publicoalvo" TEXT,
    "descricao" TEXT,
    "objetivos" TEXT,
    "nome" TEXT,
    "idcursoinep" INTEGER,
    "habilitacao" TEXT,
    "titulo" TEXT,
    "abreviatura" TEXT,
    "codigoantsei" INTEGER,
    "titulacaodoformando" TEXT,
    "numeroexemplaresbibliograficobasica" INTEGER,
    "tempodefasagempadraocatalogobibliograficabasica" INTEGER,
    "numeroexemplaresbibliograficocomplementar" INTEGER,
    "tempodefasagempadraocatalogobibliograficacomplementar" INTEGER,
    "limitardiasdownload" BOOLEAN,
    "qtdediaslimitedownload" INTEGER,
    "funcionarioresppreinscricao" INTEGER,
    "quantidadedisciplinasoptativasexpedicaodiploma" INTEGER,
    "liberarregistroaulaentreperiodo" BOOLEAN,
    "apresentarhomepreinscricao" BOOLEAN,
    "codigoant" INTEGER,
    "tabelaant" TEXT,
    "configuracaotcc" INTEGER,
    "titulacaodoformandofeminino" TEXT,
    "anomudancalegislacao" TEXT,
    "percentualevolucaoacademicaingressanteenade" INTEGER,
    "percentualevolucaoacademicaconcluinteenade" INTEGER,
    "preposicaonomecurso" TEXT,
    "nomedocumentacao" TEXT,
    "titulacaomasculinoapresentardiploma" TEXT,
    "titulacaofemininoapresentardiploma" TEXT,
    "codigocontabil" TEXT,
    "nomecontabil" TEXT,
    "apresentarcursobiblioteca" BOOLEAN,
    "dataultimaalteracao" TIMESTAMP(3),
    "nivelcontabil" TEXT,
    "modalidadecurso" TEXT,
    "utilizarrecursoavaterceiros" BOOLEAN,
    "questionario" INTEGER,
    "created" TIMESTAMP(3),
    "codigocreated" INTEGER,
    "nomecreated" TEXT,
    "updated" TIMESTAMP(3),
    "codigoupdated" INTEGER,
    "nomeupdated" TEXT,
    "textodeclaracaoppi" TEXT,
    "textodeclaracaoescolaridadepublica" TEXT,
    "textoconfirmacaonovamatricula" TEXT,
    "urldeclaracaonormasmatricula" TEXT,
    "textodeclaracaobolsasauxilios" TEXT,
    "permitirassinarcontratopendenciadocumentacao" BOOLEAN,
    "ativarprematriculaaposentregadocumentosobrigatorios" BOOLEAN,
    "possuicodigoemec" BOOLEAN,
    "codigoemec" INTEGER,
    "numeroprocessoemec" INTEGER,
    "tipoprocessoemec" TEXT,
    "datacadastroemec" TIMESTAMP(3),
    "dataprotocoloemec" TIMESTAMP(3),
    "tipoautorizacaocursoenum" TEXT,
    "numeroautorizacao" TEXT,
    "criterioavaliacao" TEXT,
    "idcrmeducacional" TEXT,
    "apresentarcursoappaluno" BOOLEAN,
    "permitirmultiplasmatriculas" BOOLEAN,
    "datacredenciamento" TIMESTAMP(3),
    "veiculopublicacao" TEXT,
    "secaopublicacao" INTEGER,
    "paginapublicacao" INTEGER,
    "numerodou" INTEGER,
    "funcionarioresptermoestagio" INTEGER,
    "grupopessoaanaliserelatorioestagio" INTEGER,
    "grupopessoaanaliseaproveitamentoestagio" INTEGER,
    "grupopessoaanalisetermoaditivoestagio" INTEGER,
    "grupopessoaanalisetermorecisaoestagio" INTEGER,
    "configuracaoestagio" INTEGER,
    "ativarmatriculaaposassinaturacontrato" BOOLEAN,
    "considerarentreguedocumentosdeferidos" BOOLEAN,
    "autorizacaoresolucaoemtramitacao" BOOLEAN,
    "numeroprocessoautorizacaoresolucao" TEXT,
    "tipoprocessoautorizacaoresolucao" TEXT,
    "datacadastroautorizacaoresolucao" TIMESTAMP(3),
    "dataprotocoloautorizacaoresolucao" TIMESTAMP(3),
    "grupopessoaanalisetermoestagio" INTEGER,
    "datahabilitacao" TIMESTAMP(3),
    "codigoplataformaa" INTEGER,
    "produtordstation" TEXT,
    "etapareferenciacampocustomizavelrdstation" TEXT,
    "idprodutordstation" TEXT,
    "formulacalculoaprovacaovestibularingressantesenem" TEXT,
    "apresentarareasitinerarias" BOOLEAN,
    "areasitinerarioformativo" TEXT,
    "tipocursoitinerarioformacaotecnicaprofissional" TEXT,
    "codigocursoitinerariotecnico" INTEGER,

    CONSTRAINT "curso_pkey" PRIMARY KEY ("codigo")
);

-- CreateTable
CREATE TABLE "negociacaocontareceber" (
    "codigo" INTEGER NOT NULL,
    "intervaloparcela" INTEGER,
    "nrparcela" INTEGER,
    "valorentrada" DECIMAL(65,30),
    "contacorrente" INTEGER,
    "centroreceita" INTEGER,
    "valortotal" DECIMAL(65,30),
    "desconto" DECIMAL(65,30),
    "multa" DOUBLE PRECISION,
    "juro" DOUBLE PRECISION,
    "valor" DECIMAL(65,30),
    "funcionario" INTEGER,
    "matriculaaluno" TEXT,
    "pessoa" INTEGER,
    "tipopessoa" TEXT,
    "unidadeensino" INTEGER,
    "responsavel" INTEGER,
    "data" TIMESTAMP(3),
    "justificativa" TEXT,
    "descontoprogressivo" INTEGER,
    "parceiro" INTEGER,
    "tipodesconto" TEXT,
    "tiporenegociacao" TEXT,
    "condicaorenegociacao" INTEGER,
    "itemcondicaorenegociacao" INTEGER,
    "liberarrenovacaoapospagamentoprimeiraparcela" BOOLEAN,
    "liberarrenovacaoapospagamentotodasparcelas" BOOLEAN,
    "fornecedor" INTEGER,
    "acrescimo" DECIMAL(65,30),
    "codigoant" INTEGER,
    "tabelaant" TEXT,
    "tipointervaloparcelaenum" TEXT,
    "databaseparcela" TIMESTAMP(3),
    "acrescimogeral" DECIMAL(65,30),
    "totalacrescimoporparcela" DECIMAL(65,30),
    "acrescimoporparcela" DECIMAL(65,30),
    "tipoacrescimoporparcela" TEXT,
    "permitirrenegociacaoapenascomcondicaorenegociacao" BOOLEAN,
    "responsavelliberacaorenegociardesativandocondicaorenegociacao" INTEGER,
    "dataliberacaorenegociardesativandocondicaorenegociacao" TIMESTAMP(3),
    "liberarrenegociardesativandocondicaorenegociacao" BOOLEAN,
    "resplibusuarionaovinculadocondrenegrealizarnegociacao" INTEGER,
    "datalibusuarionaovinculadocondrenegrealizarnegociacao" TIMESTAMP(3),
    "liberarusuarionaovinculadocondrenegrealizarnegociacao" BOOLEAN,
    "responsavelliberacaousuarionaovinculadocondicaorenegociacaoreal" INTEGER,
    "dataliberacaousuarionaovinculadocondicaorenegociacaorealizarneg" TIMESTAMP(3),
    "liberarusuarionaovinculadocondicaorenegociacaorealizarnegociaca" BOOLEAN,
    "itemcondicaodescontorenegociacao" INTEGER,
    "pessoacomissionada" INTEGER,
    "valortotaljuro" DECIMAL(65,30),
    "valorisencaototaljuro" DECIMAL(65,30),
    "valorisencaototaljuromaximo" DECIMAL(65,30),
    "valortotalmulta" DECIMAL(65,30),
    "valorisencaototalmulta" DECIMAL(65,30),
    "valorisencaototalmultamaximo" DECIMAL(65,30),
    "valortotaldescontoperdido" DECIMAL(65,30),
    "valorconcecaodescontoperdido" DECIMAL(65,30),
    "valorconcecaodescontoperdidomaximo" DECIMAL(65,30),
    "permitirpagamentocartaocreditovisaoaluno" BOOLEAN,
    "valorjurodesconto" DECIMAL(65,30),
    "valormultadesconto" DECIMAL(65,30),
    "valorindicereajustedesconto" DECIMAL(65,30),
    "agentenegativacaocobrancacontareceber" INTEGER,
    "created" TIMESTAMP(3),
    "codigocreated" INTEGER,
    "nomecreated" TEXT,
    "updated" TIMESTAMP(3),
    "codigoupdated" INTEGER,
    "nomeupdated" TEXT,
    "empresafinanceira" TEXT,
    "codigointegracaoempresafinanceira" TEXT,
    "indicereajuste" INTEGER,
    "requerimento" INTEGER,
    "codigoprotheus" TEXT,
    "codigoprocessoprotheus" TEXT,

    CONSTRAINT "negociacaocontareceber_pkey" PRIMARY KEY ("codigo")
);

-- CreateTable
CREATE TABLE "contarecebernegociado" (
    "codigo" INTEGER NOT NULL,
    "contareceber" INTEGER,
    "negociacaocontareceber" INTEGER,
    "valor" DECIMAL(65,30),
    "nrdiasatraso" DECIMAL(65,30),
    "codigoant" INTEGER,
    "tabelaant" TEXT,
    "valororiginalconta" DECIMAL(65,30),
    "valordescontoprogressivodesconsiderado" DECIMAL(65,30),
    "valordescontoalunodesconsiderado" DECIMAL(65,30),
    "valordescontoinstituicaocomvalidadedesconsiderado" DECIMAL(65,30),
    "valordescontoinstituicaosemvalidadedesconsiderado" DECIMAL(65,30),
    "desconsiderardescontoprogressivo" BOOLEAN,
    "desconsiderardescontoaluno" BOOLEAN,
    "desconsiderardescontoinstituicaocomvalidade" BOOLEAN,
    "desconsiderardescontoinstituicaosemvalidade" BOOLEAN,
    "valororiginaljuro" DECIMAL(65,30),
    "valororiginalmulta" DECIMAL(65,30),
    "itemcondicaodescontorenegociacao" INTEGER,
    "created" TIMESTAMP(3),
    "codigocreated" INTEGER,
    "nomecreated" TEXT,
    "updated" TIMESTAMP(3),
    "codigoupdated" INTEGER,
    "nomeupdated" TEXT,

    CONSTRAINT "contarecebernegociado_pkey" PRIMARY KEY ("codigo")
);

-- CreateTable
CREATE TABLE "negociacaorecebimento" (
    "codigo" INTEGER NOT NULL,
    "pessoa" INTEGER,
    "tipopessoa" TEXT,
    "matricula" TEXT,
    "contacorrentecaixa" INTEGER,
    "responsavel" INTEGER,
    "valortotal" DECIMAL(65,30),
    "valortotalrecebimento" DECIMAL(65,30),
    "valortroco" DECIMAL(65,30),
    "data" TIMESTAMP(3),
    "unidadeensino" INTEGER,
    "parceiro" INTEGER,
    "codigoantsei" INTEGER,
    "observacao" TEXT,
    "recebimentoboletoautomatico" BOOLEAN,
    "fornecedor" INTEGER,
    "codigoant" INTEGER,
    "tabelaant" TEXT,
    "codigoantflan" INTEGER,
    "pagamentocomdcc" BOOLEAN,
    "dataregistro" TIMESTAMP(3),
    "created" TIMESTAMP(3),
    "codigocreated" INTEGER,
    "nomecreated" TEXT,
    "updated" TIMESTAMP(3),
    "codigoupdated" INTEGER,
    "nomeupdated" TEXT,
    "valorestornadocartao" DECIMAL(65,30),
    "transacaoprovenienterecorrencia" BOOLEAN,
    "empresafinanceira" TEXT,
    "codigointegracaoempresafinanceira" TEXT,
    "recebimentowebhook" BOOLEAN,

    CONSTRAINT "negociacaorecebimento_pkey" PRIMARY KEY ("codigo")
);

-- CreateTable
CREATE TABLE "contarecebernegociacaorecebimento" (
    "codigo" INTEGER NOT NULL,
    "contareceber" INTEGER,
    "negociacaorecebimento" INTEGER,
    "valortotal" DECIMAL(65,30),
    "codigoantsei" INTEGER,
    "notificarserasa" BOOLEAN,
    "datanotificacaoserasa" TIMESTAMP(3),
    "codigoant" INTEGER,
    "tabelaant" TEXT,
    "contareceberterceiro" BOOLEAN,
    "created" TIMESTAMP(3),
    "codigocreated" INTEGER,
    "nomecreated" TEXT,
    "updated" TIMESTAMP(3),
    "codigoupdated" INTEGER,
    "nomeupdated" TEXT,
    "codigoprotheus" TEXT,

    CONSTRAINT "contarecebernegociacaorecebimento_pkey" PRIMARY KEY ("codigo")
);

-- CreateTable
CREATE TABLE "contareceberrecebimento" (
    "codigo" INTEGER NOT NULL,
    "formapagamento" INTEGER,
    "contareceber" INTEGER,
    "formapagamentonegociacaorecebimento" INTEGER,
    "valorrecebimento" DECIMAL(65,30),
    "negociacaorecebimento" INTEGER,
    "tiporecebimento" TEXT,
    "datarecebimento" TIMESTAMP(3),
    "responsavel" INTEGER,
    "motivo" TEXT,
    "codigoantsei" INTEGER,
    "notafiscalsaida" INTEGER,
    "contareceberoriginal" INTEGER,
    "recebimentoterceirizado" BOOLEAN,
    "notafiscalsaidaservico" INTEGER,
    "created" TIMESTAMP(3),
    "codigocreated" INTEGER,
    "nomecreated" TEXT,
    "updated" TIMESTAMP(3),
    "codigoupdated" INTEGER,
    "nomeupdated" TEXT,
    "valorestornadocartao" DECIMAL(65,30),

    CONSTRAINT "contareceberrecebimento_pkey" PRIMARY KEY ("codigo")
);

-- CreateTable
CREATE TABLE "formapagamentonegociacaorecebimento" (
    "codigo" INTEGER NOT NULL,
    "cheque" INTEGER,
    "contacorrente" INTEGER,
    "valorrecebimento" DECIMAL(65,30),
    "formapagamento" INTEGER,
    "negociacaorecebimento" INTEGER,
    "codigoantsei" INTEGER,
    "qtdeparcelascartaocredito" INTEGER,
    "operadoracartao" INTEGER,
    "taxaoperadora" DOUBLE PRECISION,
    "taxaantecipacao" DOUBLE PRECISION,
    "categoriadespesa" INTEGER,
    "contacorrenteoperadoracartao" INTEGER,
    "codigoant" INTEGER,
    "tabelaant" TEXT,
    "formapagamentonegociacaorecebimentocartaocredito" INTEGER,
    "usuariodesbloqueouformarecebimentonorecebimento" INTEGER,
    "datausuariodesbloqueouformarecebimentonorecebimento" TIMESTAMP(3),
    "configuracaorecebimentocartaocredito" INTEGER,
    "motivocancelamento" TEXT,
    "datacredito" TIMESTAMP(3),
    "created" TIMESTAMP(3),
    "codigocreated" INTEGER,
    "nomecreated" TEXT,
    "updated" TIMESTAMP(3),
    "codigoupdated" INTEGER,
    "nomeupdated" TEXT,
    "numerorecibotransacaocartaodebito" TEXT,
    "valorestornadocartao" DECIMAL(65,30),
    "formapagamentoempresafinanceira" TEXT,

    CONSTRAINT "formapagamentonegociacaorecebimento_pkey" PRIMARY KEY ("codigo")
);

-- CreateTable
CREATE TABLE "formapagamento" (
    "codigo" INTEGER NOT NULL,
    "nome" TEXT,
    "tipo" TEXT,
    "codigoantsei" INTEGER,
    "usanorecebimento" BOOLEAN,
    "codigoant" INTEGER,
    "tabelaant" TEXT,
    "created" TIMESTAMP(3),
    "codigocreated" INTEGER,
    "nomecreated" TEXT,
    "updated" TIMESTAMP(3),
    "codigoupdated" INTEGER,
    "nomeupdated" TEXT,
    "codigoprotheus" TEXT,

    CONSTRAINT "formapagamento_pkey" PRIMARY KEY ("codigo")
);

-- CreateTable
CREATE TABLE "cartaocreditodebitorecorrenciapessoa" (
    "codigo" INTEGER NOT NULL,
    "pessoa" INTEGER,
    "matricula" TEXT,
    "responsavelfinanceiro" INTEGER,
    "operadoracartao" INTEGER,
    "numerocartao" TEXT,
    "numerocartaomascarado" TEXT,
    "nomecartao" TEXT,
    "mesvalidade" INTEGER,
    "anovalidade" INTEGER,
    "codigoseguranca" TEXT,
    "formapadraodatabasecartaorecorrente" TEXT,
    "diapagamentopadrao" INTEGER,
    "situacao" TEXT,
    "datacadastro" TIMESTAMP(3),
    "algoritmocriptografia" TEXT,
    "created" TIMESTAMP(3),
    "codigocreated" INTEGER,
    "nomecreated" TEXT,
    "updated" TIMESTAMP(3),
    "codigoupdated" INTEGER,
    "nomeupdated" TEXT,
    "celularcartao" TEXT,
    "cpfcartao" TEXT,
    "emailcartao" TEXT,
    "datainativacao" TIMESTAMP(3),
    "motivoinativacao" TEXT,
    "inativadoviarecorrencia" BOOLEAN,
    "transacaocartaoonline" INTEGER,

    CONSTRAINT "cartaocreditodebitorecorrenciapessoa_pkey" PRIMARY KEY ("codigo")
);

-- CreateTable
CREATE TABLE "documentoassinadopessoa" (
    "codigo" INTEGER NOT NULL,
    "datasolicitacao" TIMESTAMP(3),
    "dataassinatura" TIMESTAMP(3),
    "datarejeicao" TIMESTAMP(3),
    "pessoa" INTEGER,
    "documentoassinado" INTEGER,
    "tipopessoa" TEXT,
    "situacaodocumentoassinadopessoa" TEXT,
    "motivorejeicao" TEXT,
    "ordemassinatura" INTEGER,
    "cargo" TEXT,
    "titulo" TEXT,
    "codigoassinatura" INTEGER,
    "acaoassinatura" TEXT,
    "urlassinatura" TEXT,
    "created" TIMESTAMP(3),
    "codigocreated" INTEGER,
    "nomecreated" TEXT,
    "updated" TIMESTAMP(3),
    "codigoupdated" INTEGER,
    "nomeupdated" TEXT,
    "assinarporcnpj" BOOLEAN,
    "provedorassinatura" TEXT,
    "possuiassinaturaautomatica" BOOLEAN,
    "nome" TEXT,
    "nomemembrocomunidade" TEXT,
    "cpfmembrocomunidade" TEXT,
    "emailmembrocomunidade" TEXT,
    "pathurlacessoexterno" TEXT,
    "documentoassinadoorigemenum" TEXT,
    "jsonassinatura" TEXT,
    "tipoassinaturadocumentoenum" TEXT,

    CONSTRAINT "documentoassinadopessoa_pkey" PRIMARY KEY ("codigo")
);

-- CreateTable
CREATE TABLE "documentoassinado" (
    "codigo" INTEGER NOT NULL,
    "dataregistro" TIMESTAMP(3),
    "usuario" INTEGER,
    "arquivo" INTEGER,
    "tipoorigemdocumentoassinado" TEXT,
    "ano" TEXT,
    "semestre" TEXT,
    "matricula" TEXT,
    "gradecurricular" INTEGER,
    "turma" INTEGER,
    "disciplina" INTEGER,
    "unidadeensino" INTEGER,
    "matriculaperiodo" INTEGER,
    "provedordeassinaturaenum" TEXT,
    "codigoprovedordeassinatura" INTEGER,
    "chaveprovedordeassinatura" TEXT,
    "urlprovedordeassinatura" TEXT,
    "created" TIMESTAMP(3),
    "codigocreated" INTEGER,
    "nomecreated" TEXT,
    "updated" TIMESTAMP(3),
    "codigoupdated" INTEGER,
    "nomeupdated" TEXT,
    "revalidacaomatricula" INTEGER,
    "bloqueadopor" INTEGER,
    "databloqueio" TIMESTAMP(3),
    "origembloqueio" TEXT,
    "curso" INTEGER,
    "programacaoformatura" INTEGER,
    "planoensino" INTEGER,
    "documentoassinadoinvalido" BOOLEAN,
    "motivodocumentoassinadoinvalido" TEXT,
    "arquivovisual" INTEGER,
    "codigovalidacaohistoricodigital" TEXT,
    "decisaojudicial" BOOLEAN,
    "versaodiploma" TEXT,
    "expedicaodiploma" INTEGER,
    "inclusaohistoricoforaprazo" INTEGER,
    "negociacaocontareceber" INTEGER,
    "codigovalidacaocurriculoescolardigital" TEXT,
    "contapagar" INTEGER,
    "registrardocumentoassinadocertifikedu" BOOLEAN,
    "codigoregistrocertifikedu" TEXT,
    "erroregistrocertifikedu" TEXT,
    "dataexpiracaodocumentocertifikedu" TIMESTAMP(3),
    "tipocontrato" TEXT,
    "lotediplomasanulados" INTEGER,
    "arquivofiscalizacao" INTEGER,
    "iddadosregistrodiplomadigital" INTEGER,
    "provedorcarimbotempo" TEXT,
    "erroregistrarprovedorcarimbotempo" TEXT,
    "enviarmensagemnotificacao" BOOLEAN,

    CONSTRAINT "documentoassinado_pkey" PRIMARY KEY ("codigo")
);

-- CreateTable
CREATE TABLE "condicaopagamentoplanofinanceirocurso" (
    "codigo" INTEGER NOT NULL,
    "restituirdiferencavalormatriculasistemaporcredito" BOOLEAN,
    "valorunitariocredito" DECIMAL(65,30),
    "valorminimoparcelasistemaporcredito" DECIMAL(65,30),
    "valormatriculasistemaporcredito" DECIMAL(65,30),
    "planodescontopadrao" INTEGER,
    "descontoprogressivopadrao" INTEGER,
    "nrparcelasperiodo" INTEGER,
    "valorparcela" DECIMAL(65,30),
    "valormatricula" DECIMAL(65,30),
    "descricao" TEXT,
    "nomeformula" TEXT,
    "formulacalculovalorfinal" TEXT,
    "formulausovariavel1" TEXT,
    "formulacalculovariavel1" TEXT,
    "utilizarvariavel1" BOOLEAN,
    "variavel1" DOUBLE PRECISION,
    "formulausovariavel2" TEXT,
    "formulacalculovariavel2" TEXT,
    "utilizarvariavel2" BOOLEAN,
    "variavel2" DOUBLE PRECISION,
    "formulausovariavel3" TEXT,
    "formulacalculovariavel3" TEXT,
    "utilizarvariavel3" BOOLEAN,
    "variavel3" DOUBLE PRECISION,
    "titulovariavel1" TEXT,
    "titulovariavel2" TEXT,
    "titulovariavel3" TEXT,
    "planofinanceirocurso" INTEGER,
    "valorfixodisciplinaincluida" DECIMAL(65,30),
    "valordescontodisciplinaexcluida" DECIMAL(65,30),
    "gerarparcelasseparadasparadisciplinasincluidas" BOOLEAN,
    "utilizarvalormatriculafixo" BOOLEAN,
    "gerarcobrancapordisciplinasincluidas" BOOLEAN,
    "gerardescontopordiscipliaexcluidas" BOOLEAN,
    "gerardescontopordisciplinexcluidassomenteultimoperiodo" BOOLEAN,
    "numeromaximodisciplinacursarparagerardescontos" INTEGER,
    "ratiarvalordiferencainclusaoexclusaoparatodasparcelas" BOOLEAN,
    "descricaoduracao" TEXT,
    "textopadraocontratomatricula" INTEGER,
    "descontoprogressivopadraomatricula" INTEGER,
    "codigoantsei" INTEGER,
    "situacao" TEXT,
    "dataativacao" TIMESTAMP(3),
    "responsavelativacao" INTEGER,
    "datainativacao" TIMESTAMP(3),
    "responsavelinativacao" INTEGER,
    "naocontrolarmatricula" BOOLEAN,
    "apresentarcondicaovisaoaluno" BOOLEAN,
    "definirplanodescontoapresentarmatricula" BOOLEAN,
    "naoregerarparcelavencida" BOOLEAN,
    "centroreceita" INTEGER,
    "aplicarcalculocombasedescontoscalculados" BOOLEAN,
    "descontoprogressivoprimeiraparcela" INTEGER,
    "tipousocondicaopagamento" TEXT,
    "tipocobrancainclusaodisciplinaregular" TEXT,
    "cobrardiscipregularquandoultrapassarcreditoschmaxperiodoletivo" BOOLEAN,
    "tipocobrancainclusaodisciplinadependencia" TEXT,
    "cobrardiscipdependenciaquandoultrapassarcreditoschmaxperlet" BOOLEAN,
    "tipocalculoparcela" TEXT,
    "valorporatividadecomplementar" DECIMAL(65,30),
    "tipocobrancaatividadecomplementar" TEXT,
    "nrcreditoporatividadecomplementar" INTEGER,
    "tipocobrancaenade" TEXT,
    "nrcreditoporenade" INTEGER,
    "valorporenade" DECIMAL(65,30),
    "tipocobrancaestagio" TEXT,
    "nrcreditoporestagio" INTEGER,
    "valorporestagio" DECIMAL(65,30),
    "valorfixodisciplinaincluidaead" DECIMAL(65,30),
    "utilizarpoliticacobrancaespecificaparaoptativas" BOOLEAN,
    "tipocobrancadisciplinaoptativa" TEXT,
    "cobrardiscipoptativaquandoultrapassarcredchmaxperlet" BOOLEAN,
    "valordisciplinaoptativa" DECIMAL(65,30),
    "valordisciplinaoptativaead" DECIMAL(65,30),
    "valordisciplinaincluidadependencia" DECIMAL(65,30),
    "valordisciplinaincluidadependenciaead" DECIMAL(65,30),
    "utilizarpoliticadescontodiscipregularfeitasviaead" BOOLEAN,
    "tipodescontodisciplinaregularead" TEXT,
    "valordescontodisciplinaregularead" DECIMAL(65,30),
    "tipocobrancaexclusaodisciplinaregular" TEXT,
    "valorfixodisciplinaexcluidaead" DECIMAL(65,30),
    "apresentarsomenteparadeterminadaformaingresso" BOOLEAN,
    "apresentarsomenteparaingressantenosemestreano" BOOLEAN,
    "formaingressoentrevista" BOOLEAN,
    "formaingressoportadordiploma" BOOLEAN,
    "formaingressotransferenciainterna" BOOLEAN,
    "formaingressoprocessoseletivo" BOOLEAN,
    "formaingressotransferenciaexterna" BOOLEAN,
    "formaingressoreingresso" BOOLEAN,
    "formaingressoprouni" BOOLEAN,
    "formaingressoenem" BOOLEAN,
    "formaingressooutrotiposelecao" BOOLEAN,
    "apresentarsomenteparaalunosintegralizandocurso" BOOLEAN,
    "considerarintegralizandoestivercursandoultimoper2vez" BOOLEAN,
    "tipocontrolealunointegralizandocurso" TEXT,
    "valorbasedefiniralunointegralizandocurso" DECIMAL(65,30),
    "permiterecebimentoonlinecartaocredito" BOOLEAN,
    "apresentarmatriculaonlineexterna" BOOLEAN,
    "apresentarmatriculaonlineprofessor" BOOLEAN,
    "apresentarmatriculaonlinecoordenador" BOOLEAN,
    "considerarvalorrateiobaseadovalorbasecomdescontosaplicados" BOOLEAN,
    "abatervalorrateirocomodescontorateio" BOOLEAN,
    "gerarparcelasextrasseparadomensalidadeareceber" BOOLEAN,
    "considerarvalorrateioextraparcelavencida" BOOLEAN,
    "categoria" TEXT,
    "naocontrolarvalorparcela" BOOLEAN,
    "gerarparcelamaterialdidatico" BOOLEAN,
    "usarunidadeensinoespecifica" BOOLEAN,
    "controladiabasevencimentoparcelamaterialdidatico" BOOLEAN,
    "aplicardescontosparcelasnomaterialdidatico" BOOLEAN,
    "aplicardescontomaterialdidaticodescontoaluno" BOOLEAN,
    "aplicardescontomaterialdidaticodescontoinstitucional" BOOLEAN,
    "aplicardescontomaterialdidaticodescontoprogressivo" BOOLEAN,
    "aplicardescontomaterialdidaticodescontoconvenio" BOOLEAN,
    "aplicardescontosdesconsiderandosvencimento" BOOLEAN,
    "unidadeensinofinanceira" BIGINT,
    "quantidadeparcelasmaterialdidatico" BIGINT,
    "diabasevencimentoparcelaoutraunidade" BIGINT,
    "valorporparcelamaterialdidatico" DECIMAL(65,30),
    "tipogeracaomaterialdidatico" TEXT,
    "apresentarcondpagtocrm" BOOLEAN,
    "regerarfinanceiro" BOOLEAN,
    "apresentarsomentepararenovacoesnosemestreano" BOOLEAN,
    "aplicardescontomateiraldidaticodescontoaluno" BOOLEAN,
    "aplicardescontomateiraldidaticodescontoinstitucional" BOOLEAN,
    "aplicardescontomateiraldidaticodescontoprogressivo" BOOLEAN,
    "aplicardescontomateiraldidaticodescontoconvenio" BOOLEAN,
    "quantidadeparcelasmateriadidatico" BIGINT,
    "lancarvalorratiadosobrevalorbasecontareceber" BOOLEAN,
    "valorprimeiraparcela" DECIMAL(65,30),
    "usavalorprimeiraparcela" BOOLEAN,
    "vencimentoprimeiraparcelaantesmaterialdidatico" BOOLEAN,
    "considerarparcelasmaterialdidaticoreajustepreco" BOOLEAN,
    "created" TIMESTAMP(3),
    "codigocreated" INTEGER,
    "nomecreated" TEXT,
    "updated" TIMESTAMP(3),
    "codigoupdated" INTEGER,
    "nomeupdated" TEXT,
    "formulausovariavel4" TEXT,
    "formulacalculovariavel4" TEXT,
    "titulovariavel4" TEXT,
    "formulacalculoparcelaperiodo" TEXT,
    "tipoparcelaperiodoenum" TEXT,
    "variavel4" DECIMAL(65,30),
    "utilizarvariavel4" BOOLEAN,
    "gerarparcelasaposassinaturacontrato" BOOLEAN,

    CONSTRAINT "condicaopagamentoplanofinanceirocurso_pkey" PRIMARY KEY ("codigo")
);

-- CreateTable
CREATE TABLE "planodescontocontareceber" (
    "codigo" INTEGER NOT NULL,
    "contareceber" INTEGER,
    "planodesconto" INTEGER,
    "tipoitemplanofinanceiro" TEXT,
    "convenio" INTEGER,
    "valorutilizadorecebimento" DECIMAL(65,30),
    "diasvalidadevencimento" INTEGER,
    "tipodesconto" TEXT,
    "valordesconto" DECIMAL(65,30),
    "ordemprioridadeparacalculo" INTEGER,
    "imposto" INTEGER,
    "aplicarsobrevalorcheio" BOOLEAN,
    "aplicarsobrevalorbasededuzidovaloroutrosplanosdesconto" BOOLEAN,
    "utilizardiautil" BOOLEAN,
    "utilizardiafixo" BOOLEAN,
    "descontovalidoatedatavencimento" BOOLEAN,
    "usuarioresponsavel" INTEGER,
    "dataconcessaodesconto" TIMESTAMP(3),
    "observacaodesconto" TEXT,
    "nome" TEXT,
    "suspensofinanciamentoproprio" BOOLEAN,
    "utilizaravancodiautil" BOOLEAN,
    "created" TIMESTAMP(3),
    "codigocreated" INTEGER,
    "nomecreated" TEXT,
    "updated" TIMESTAMP(3),
    "codigoupdated" INTEGER,
    "nomeupdated" TEXT,
    "custeaparcelasmaterialdidatico" BOOLEAN,
    "categoriadesconto" INTEGER,

    CONSTRAINT "planodescontocontareceber_pkey" PRIMARY KEY ("codigo")
);

-- CreateTable
CREATE TABLE "planodesconto" (
    "codigo" INTEGER NOT NULL,
    "descricao" TEXT,
    "requisitos" TEXT,
    "somente1periodoletivomatricula" BOOLEAN,
    "percdescontomatricula" DOUBLE PRECISION,
    "somente1periodoletivoparcela" BOOLEAN,
    "percdescontoparcela" DOUBLE PRECISION,
    "nome" TEXT,
    "tipodescontoparcela" TEXT,
    "tipodescontomatricula" TEXT,
    "diasvalidadevencimento" INTEGER,
    "codigoantsei" INTEGER,
    "ativo" BOOLEAN,
    "responsavelativacao" INTEGER,
    "datainativacao" TIMESTAMP(3),
    "responsavelinativacao" INTEGER,
    "dataativacao" TIMESTAMP(3),
    "descontovalidoatedatavencimento" BOOLEAN,
    "unidadeensino" INTEGER,
    "aplicarsobrevalorcheio" BOOLEAN,
    "utilizardiautil" BOOLEAN,
    "utilizardiafixo" BOOLEAN,
    "aplicarsobrevalorbasededuzidovaloroutrosplanosdesconto" BOOLEAN,
    "ordemprioridadeparacalculo" INTEGER,
    "categoriadesconto" INTEGER,
    "bolsafilantropia" BOOLEAN,
    "removerdescontorenovacao" BOOLEAN,
    "aplicardescontoapartirparcela" INTEGER,
    "utilizaravancodiautil" BOOLEAN,
    "created" TIMESTAMP(3),
    "codigocreated" INTEGER,
    "nomecreated" TEXT,
    "updated" TIMESTAMP(3),
    "codigoupdated" INTEGER,
    "nomeupdated" TEXT,
    "aplicardescontoateparcela" INTEGER,

    CONSTRAINT "planodesconto_pkey" PRIMARY KEY ("codigo")
);

-- CreateTable
CREATE TABLE "funcionario" (
    "codigo" INTEGER NOT NULL,
    "matricula" TEXT,
    "pessoa" INTEGER,
    "dataadmissao" TIMESTAMP(3),
    "exercecargoadministrativo" BOOLEAN,
    "nomebanco" TEXT,
    "numerobancorecebimento" TEXT,
    "numeroagenciarecebimento" TEXT,
    "contacorrenterecebimento" TEXT,
    "codigoant" INTEGER,
    "codigoantsei" INTEGER,
    "remover" BOOLEAN,
    "observacao" TEXT,
    "escolaridade" TEXT,
    "arquivoassinatura" INTEGER,
    "empresarecebimento" TEXT,
    "cnpjempresarecebimento" TEXT,
    "digitoagenciarecebimento" TEXT,
    "digitocorrenterecebimento" TEXT,
    "operacaobancaria" TEXT,
    "chaveenderecamentopix" TEXT,
    "tipoidentificacaochavepixenum" TEXT,
    "created" TIMESTAMP(3),
    "codigocreated" INTEGER,
    "nomecreated" TEXT,
    "updated" TIMESTAMP(3),
    "codigoupdated" INTEGER,
    "nomeupdated" TEXT,
    "utilizarcertificadoproprio" BOOLEAN,
    "certificadodigital" INTEGER,
    "senhacertificadodigital" TEXT,
    "horassemanaiscontratada" INTEGER,
    "regime" TEXT,

    CONSTRAINT "funcionario_pkey" PRIMARY KEY ("codigo")
);

-- CreateTable
CREATE TABLE "pf_alunos" (
    "matricula" TEXT NOT NULL,
    "nome" TEXT,
    "telefone" TEXT,
    "email" TEXT,
    "parcelas_pagas" INTEGER,
    "parcelas_atraso" INTEGER,
    "parcelas_aberto" INTEGER,
    "aulas_total_porcentagem" DOUBLE PRECISION,
    "id" BIGINT,
    "turma" TEXT,
    "criado_em" TEXT,
    "dias_desde_primeira_aula" INTEGER,
    "dias_desde_ultima_aula" INTEGER,
    "aulas_assistidas" INTEGER,
    "status_financeiro" TEXT,
    "cidade" TEXT,
    "tag" TEXT,
    "cep" TEXT,

    CONSTRAINT "pf_alunos_pkey" PRIMARY KEY ("matricula")
);

-- CreateTable
CREATE TABLE "pf_plantoes" (
    "id" SERIAL NOT NULL,
    "data_plantao" TEXT,
    "data_marcado" TEXT,
    "matricula" TEXT NOT NULL,
    "nome" TEXT,
    "telefone" TEXT,
    "status" TEXT,
    "moscow" TEXT,

    CONSTRAINT "pf_plantoes_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "serasa" (
    "id" SERIAL NOT NULL,
    "cpf_cnpj" TEXT NOT NULL,
    "cpf_cnpj_numerico" TEXT NOT NULL,
    "nome" TEXT,
    "contrato" TEXT,
    "valor" TEXT,
    "valor_numerico" DOUBLE PRECISION,
    "enviado_em" TEXT,
    "baixado_em" TEXT,
    "situacao" TEXT,

    CONSTRAINT "serasa_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "blip_contacts" (
    "identity" TEXT NOT NULL,
    "name" TEXT,
    "phoneNumber" TEXT,
    "cpf" TEXT,
    "cpf_sanitizado" TEXT,
    "telefone_sanitizado" TEXT,

    CONSTRAINT "blip_contacts_pkey" PRIMARY KEY ("identity")
);

-- CreateTable
CREATE TABLE "blip_tickets" (
    "id" TEXT NOT NULL,
    "sequentialId" INTEGER,
    "customerIdentity" TEXT,
    "agentIdentity" TEXT,
    "status" TEXT,
    "storageDate" TEXT,
    "team" TEXT,
    "closed" INTEGER,
    "priority" INTEGER,

    CONSTRAINT "blip_tickets_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "User_email_key" ON "User"("email");

-- CreateIndex
CREATE UNIQUE INDEX "contareceber_codigobarra_key" ON "contareceber"("codigobarra");

-- CreateIndex
CREATE UNIQUE INDEX "contareceber_nossonumero_contacorrente_key" ON "contareceber"("nossonumero", "contacorrente");

-- CreateIndex
CREATE UNIQUE INDEX "pessoa_cpf_key" ON "pessoa"("cpf");

-- CreateIndex
CREATE UNIQUE INDEX "pessoa_cnpj_key" ON "pessoa"("cnpj");

-- CreateIndex
CREATE UNIQUE INDEX "turma_identificadorturma_key" ON "turma"("identificadorturma");

-- CreateIndex
CREATE UNIQUE INDEX "curso_nome_habilitacao_key" ON "curso"("nome", "habilitacao");

-- CreateIndex
CREATE UNIQUE INDEX "contarecebernegociacaorecebimento_contareceber_key" ON "contarecebernegociacaorecebimento"("contareceber");

-- CreateIndex
CREATE UNIQUE INDEX "formapagamento_nome_key" ON "formapagamento"("nome");

-- CreateIndex
CREATE UNIQUE INDEX "planodesconto_nome_key" ON "planodesconto"("nome");

-- CreateIndex
CREATE UNIQUE INDEX "funcionario_matricula_key" ON "funcionario"("matricula");

-- CreateIndex
CREATE UNIQUE INDEX "pf_plantoes_matricula_data_plantao_key" ON "pf_plantoes"("matricula", "data_plantao");

-- CreateIndex
CREATE UNIQUE INDEX "serasa_cpf_cnpj_numerico_contrato_enviado_em_key" ON "serasa"("cpf_cnpj_numerico", "contrato", "enviado_em");
